// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/ironpass/Agents.tsx": () => import("../components/mockups/ironpass/Agents.tsx"),
  "./components/mockups/ironpass/ApiKeys.tsx": () => import("../components/mockups/ironpass/ApiKeys.tsx"),
  "./components/mockups/ironpass/AuditLog.tsx": () => import("../components/mockups/ironpass/AuditLog.tsx"),
  "./components/mockups/ironpass/Dashboard.tsx": () => import("../components/mockups/ironpass/Dashboard.tsx"),
  "./components/mockups/ironpass/Frameworks.tsx": () => import("../components/mockups/ironpass/Frameworks.tsx"),
  "./components/mockups/ironpass/Governance.tsx": () => import("../components/mockups/ironpass/Governance.tsx"),
  "./components/mockups/ironpass/Guardrails.tsx": () => import("../components/mockups/ironpass/Guardrails.tsx"),
  "./components/mockups/ironpass/Policies.tsx": () => import("../components/mockups/ironpass/Policies.tsx"),
  "./components/mockups/ironpass/Reports.tsx": () => import("../components/mockups/ironpass/Reports.tsx"),
  "./components/mockups/ironpass/Settings.tsx": () => import("../components/mockups/ironpass/Settings.tsx"),
  "./components/mockups/ironpass/Team.tsx": () => import("../components/mockups/ironpass/Team.tsx"),
  "./components/mockups/ironpass/TestConsole.tsx": () => import("../components/mockups/ironpass/TestConsole.tsx"),
  "./components/mockups/ironpass/Violations.tsx": () => import("../components/mockups/ironpass/Violations.tsx")
};
