// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/covenant/AgentSecuritySuite.tsx": () => import("../components/mockups/covenant/AgentSecuritySuite.tsx"),
  "./components/mockups/covenant/Agents.tsx": () => import("../components/mockups/covenant/Agents.tsx"),
  "./components/mockups/covenant/ApiKeys.tsx": () => import("../components/mockups/covenant/ApiKeys.tsx"),
  "./components/mockups/covenant/AuditLog.tsx": () => import("../components/mockups/covenant/AuditLog.tsx"),
  "./components/mockups/covenant/ComplianceLayer.tsx": () => import("../components/mockups/covenant/ComplianceLayer.tsx"),
  "./components/mockups/covenant/Dashboard.tsx": () => import("../components/mockups/covenant/Dashboard.tsx"),
  "./components/mockups/covenant/Frameworks.tsx": () => import("../components/mockups/covenant/Frameworks.tsx"),
  "./components/mockups/covenant/FunctionsAndTools.tsx": () => import("../components/mockups/covenant/FunctionsAndTools.tsx"),
  "./components/mockups/covenant/GovAnalytics.tsx": () => import("../components/mockups/covenant/GovAnalytics.tsx"),
  "./components/mockups/covenant/Governance.tsx": () => import("../components/mockups/covenant/Governance.tsx"),
  "./components/mockups/covenant/Guardrails.tsx": () => import("../components/mockups/covenant/Guardrails.tsx"),
  "./components/mockups/covenant/IndustrySuites.tsx": () => import("../components/mockups/covenant/IndustrySuites.tsx"),
  "./components/mockups/covenant/Legal.tsx": () => import("../components/mockups/covenant/Legal.tsx"),
  "./components/mockups/covenant/Login.tsx": () => import("../components/mockups/covenant/Login.tsx"),
  "./components/mockups/covenant/OperationsFunctions.tsx": () => import("../components/mockups/covenant/OperationsFunctions.tsx"),
  "./components/mockups/covenant/Policies.tsx": () => import("../components/mockups/covenant/Policies.tsx"),
  "./components/mockups/covenant/Reports.tsx": () => import("../components/mockups/covenant/Reports.tsx"),
  "./components/mockups/covenant/Settings.tsx": () => import("../components/mockups/covenant/Settings.tsx"),
  "./components/mockups/covenant/Team.tsx": () => import("../components/mockups/covenant/Team.tsx"),
  "./components/mockups/covenant/TestConsole.tsx": () => import("../components/mockups/covenant/TestConsole.tsx"),
  "./components/mockups/covenant/Violations.tsx": () => import("../components/mockups/covenant/Violations.tsx"),
  "./components/mockups/covenant/Workspaces.tsx": () => import("../components/mockups/covenant/Workspaces.tsx")
};
