"""Add SLA audit columns

Revision ID: 0dc5bec7523d
Revises: b49cd746a4f6
Create Date: 2026-09-15 12:47:27.524004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0dc5bec7523d'
down_revision: Union[str, None] = 'b49cd746a4f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('tenant_deletion_job_steps_job_id_fkey', 'tenant_deletion_job_steps', type_='foreignkey')
    op.create_foreign_key(None, 'tenant_deletion_job_steps', 'tenant_deletion_jobs', ['job_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint('tenant_deletion_jobs_tenant_id_fkey', 'tenant_deletion_jobs', type_='foreignkey')
    op.create_foreign_key(None, 'tenant_deletion_jobs', 'tenants', ['tenant_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint('tenant_policy_versions_tenant_id_fkey', 'tenant_policy_versions', type_='foreignkey')
    op.create_foreign_key(None, 'tenant_policy_versions', 'tenants', ['tenant_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint('users_tenant_id_fkey', 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'tenants', ['tenant_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.add_column('audit_log', sa.Column('prompt_tokens', sa.Integer(), nullable=True), schema='audit')
    op.add_column('audit_log', sa.Column('completion_tokens', sa.Integer(), nullable=True), schema='audit')
    op.add_column('audit_log', sa.Column('total_tokens', sa.Integer(), nullable=True), schema='audit')
    op.add_column('audit_log', sa.Column('model', sa.String(length=128), nullable=True), schema='audit')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('audit_log', 'model', schema='audit')
    op.drop_column('audit_log', 'total_tokens', schema='audit')
    op.drop_column('audit_log', 'completion_tokens', schema='audit')
    op.drop_column('audit_log', 'prompt_tokens', schema='audit')
    op.drop_constraint(None, 'users', schema='public', type_='foreignkey')
    op.create_foreign_key('users_tenant_id_fkey', 'users', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'tenant_policy_versions', schema='public', type_='foreignkey')
    op.create_foreign_key('tenant_policy_versions_tenant_id_fkey', 'tenant_policy_versions', 'tenants', ['tenant_id'], ['id'])
    op.drop_constraint(None, 'tenant_deletion_jobs', schema='public', type_='foreignkey')
    op.create_foreign_key('tenant_deletion_jobs_tenant_id_fkey', 'tenant_deletion_jobs', 'tenants', ['tenant_id'], ['id'])
    op.drop_constraint(None, 'tenant_deletion_job_steps', schema='public', type_='foreignkey')
    op.create_foreign_key('tenant_deletion_job_steps_job_id_fkey', 'tenant_deletion_job_steps', 'tenant_deletion_jobs', ['job_id'], ['id'])
    # ### end Alembic commands ###
