"""Add SLA models

Revision ID: 4621c16205c1
Revises: 0dc5bec7523d
Create Date: 2026-09-15 12:59:35.350800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4621c16205c1'
down_revision: Union[str, None] = '0dc5bec7523d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE SCHEMA IF NOT EXISTS sla')
    op.create_table('sla_policy',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('metric_type', sa.String(length=32), nullable=False),
    sa.Column('threshold_value', sa.Float(), nullable=False),
    sa.Column('window_minutes', sa.Integer(), nullable=False),
    sa.Column('notification_email', sa.String(length=256), nullable=True),
    sa.Column('webhook_url', sa.String(length=1024), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='sla'
    )
    op.create_index('idx_sla_policy_active', 'sla_policy', ['is_active'], unique=False, schema='sla')
    op.create_index('idx_sla_policy_tenant', 'sla_policy', ['tenant_id'], unique=False, schema='sla')
    op.create_table('sla_breach',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('policy_id', sa.UUID(), nullable=False),
    sa.Column('breached_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metric_value', sa.Float(), nullable=False),
    sa.Column('threshold_value', sa.Float(), nullable=False),
    sa.Column('notification_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['policy_id'], ['sla.sla_policy.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='sla'
    )
    op.create_index('idx_sla_breach_policy', 'sla_breach', ['policy_id'], unique=False, schema='sla')
    op.create_index('idx_sla_breach_resolved', 'sla_breach', ['resolved_at'], unique=False, schema='sla')
    op.create_index('idx_sla_breach_tenant', 'sla_breach', ['tenant_id'], unique=False, schema='sla')
    op.drop_constraint('tenant_deletion_job_steps_job_id_fkey', 'tenant_deletion_job_steps', type_='foreignkey')
    op.create_foreign_key(None, 'tenant_deletion_job_steps', 'tenant_deletion_jobs', ['job_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint('tenant_deletion_jobs_tenant_id_fkey', 'tenant_deletion_jobs', type_='foreignkey')
    op.create_foreign_key(None, 'tenant_deletion_jobs', 'tenants', ['tenant_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint('tenant_policy_versions_tenant_id_fkey', 'tenant_policy_versions', type_='foreignkey')
    op.create_foreign_key(None, 'tenant_policy_versions', 'tenants', ['tenant_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint('users_tenant_id_fkey', 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'tenants', ['tenant_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', schema='public', type_='foreignkey')
    op.create_foreign_key('users_tenant_id_fkey', 'users', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'tenant_policy_versions', schema='public', type_='foreignkey')
    op.create_foreign_key('tenant_policy_versions_tenant_id_fkey', 'tenant_policy_versions', 'tenants', ['tenant_id'], ['id'])
    op.drop_constraint(None, 'tenant_deletion_jobs', schema='public', type_='foreignkey')
    op.create_foreign_key('tenant_deletion_jobs_tenant_id_fkey', 'tenant_deletion_jobs', 'tenants', ['tenant_id'], ['id'])
    op.drop_constraint(None, 'tenant_deletion_job_steps', schema='public', type_='foreignkey')
    op.create_foreign_key('tenant_deletion_job_steps_job_id_fkey', 'tenant_deletion_job_steps', 'tenant_deletion_jobs', ['job_id'], ['id'])
    op.drop_index('idx_sla_breach_tenant', table_name='sla_breach', schema='sla')
    op.drop_index('idx_sla_breach_resolved', table_name='sla_breach', schema='sla')
    op.drop_index('idx_sla_breach_policy', table_name='sla_breach', schema='sla')
    op.drop_table('sla_breach', schema='sla')
    op.drop_index('idx_sla_policy_tenant', table_name='sla_policy', schema='sla')
    op.drop_index('idx_sla_policy_active', table_name='sla_policy', schema='sla')
    op.drop_table('sla_policy', schema='sla')
    # ### end Alembic commands ###
