"""add_tenant_policy_versions

Revision ID: 63ca5818a477
Revises: e9c8e6bbe7a9
Create Date: 2026-05-21 00:50:38.553828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '63ca5818a477'
down_revision: Union[str, None] = 'e9c8e6bbe7a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenant_policy_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('policy', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('change_summary', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('activated_by', sa.Text(), nullable=True),
    sa.Column('superseded_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['public.tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'version', name='uq_tenant_policy_version'),
    schema='public'
    )
    op.create_index('uq_one_active_policy_per_tenant', 'tenant_policy_versions', ['tenant_id'], unique=True, schema='public', postgresql_where=sa.text('is_active = true'))
    op.drop_constraint('tenant_deletion_job_steps_job_id_fkey', 'tenant_deletion_job_steps', type_='foreignkey')
    op.create_foreign_key(None, 'tenant_deletion_job_steps', 'tenant_deletion_jobs', ['job_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint('tenant_deletion_jobs_tenant_id_fkey', 'tenant_deletion_jobs', type_='foreignkey')
    op.create_foreign_key(None, 'tenant_deletion_jobs', 'tenants', ['tenant_id'], ['id'], source_schema='public', referent_schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tenant_deletion_jobs', schema='public', type_='foreignkey')
    op.create_foreign_key('tenant_deletion_jobs_tenant_id_fkey', 'tenant_deletion_jobs', 'tenants', ['tenant_id'], ['id'])
    op.drop_constraint(None, 'tenant_deletion_job_steps', schema='public', type_='foreignkey')
    op.create_foreign_key('tenant_deletion_job_steps_job_id_fkey', 'tenant_deletion_job_steps', 'tenant_deletion_jobs', ['job_id'], ['id'])
    op.drop_index('uq_one_active_policy_per_tenant', table_name='tenant_policy_versions', schema='public', postgresql_where=sa.text('is_active = true'))
    op.drop_table('tenant_policy_versions', schema='public')
    # ### end Alembic commands ###
