"""add missing application schema

Revision ID: 8080de9936a5
Revises: 8f91c7d84c21
Create Date: 2026-05-21 00:17:29.810596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8080de9936a5'
down_revision: Union[str, None] = '8f91c7d84c21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE SCHEMA IF NOT EXISTS vault")
    op.create_table('agent_security_decision_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('request_id', sa.String(length=128), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('overall_risk_score', sa.Integer(), nullable=False),
    sa.Column('decision_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('signature', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index('idx_agent_sec_decision_tenant_action', 'agent_security_decision_logs', ['tenant_id', 'action'], unique=False, schema='public')
    op.create_index('idx_agent_sec_decision_tenant_created', 'agent_security_decision_logs', ['tenant_id', 'created_at'], unique=False, schema='public')
    op.create_index('idx_agent_sec_decision_tenant_request', 'agent_security_decision_logs', ['tenant_id', 'request_id'], unique=True, schema='public')
    op.create_table('agent_security_policies',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_by', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index('idx_agent_sec_policy_tenant', 'agent_security_policies', ['tenant_id'], unique=True, schema='public')
    op.create_table('aml_signals',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('subject_id', sa.String(length=128), nullable=True),
    sa.Column('counterparty', sa.String(length=255), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('country_from', sa.String(length=2), nullable=True),
    sa.Column('country_to', sa.String(length=2), nullable=True),
    sa.Column('channel', sa.String(length=32), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('flags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('related_case_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index('idx_aml_signal_tenant_created', 'aml_signals', ['tenant_id', 'created_at'], unique=False, schema='public')
    op.create_index('idx_aml_signal_tenant_status', 'aml_signals', ['tenant_id', 'status'], unique=False, schema='public')
    op.create_table('competitor_profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('competitor_name', sa.String(length=255), nullable=False),
    sa.Column('segment', sa.String(length=128), nullable=True),
    sa.Column('strategic_priority', sa.String(length=32), nullable=False),
    sa.Column('owner', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index('idx_competitor_profile_tenant_name', 'competitor_profiles', ['tenant_id', 'competitor_name'], unique=False, schema='public')
    op.create_index('idx_competitor_profile_tenant_status', 'competitor_profiles', ['tenant_id', 'status'], unique=False, schema='public')
    op.create_table('competitor_signal_assessments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('assessment_batch_id', sa.String(length=36), nullable=False),
    sa.Column('competitor_id', sa.String(length=36), nullable=True),
    sa.Column('competitor_name', sa.String(length=255), nullable=False),
    sa.Column('signal_type', sa.String(length=64), nullable=False),
    sa.Column('signal_strength', sa.Integer(), nullable=False),
    sa.Column('source_confidence_pct', sa.Numeric(precision=8, scale=3), nullable=False),
    sa.Column('revenue_impact_pct', sa.Numeric(precision=8, scale=3), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('priority_score', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('reasons', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index('idx_comp_signal_tenant_batch', 'competitor_signal_assessments', ['tenant_id', 'assessment_batch_id'], unique=False, schema='public')
    op.create_index('idx_comp_signal_tenant_status_created', 'competitor_signal_assessments', ['tenant_id', 'status', 'created_at'], unique=False, schema='public')
    op.create_table('compliance_case_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('event_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index('idx_case_event_tenant_case_created', 'compliance_case_events', ['tenant_id', 'case_id', 'created_at'], unique=False, schema='public')
    op.create_table('compliance_cases',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('domain', sa.String(length=64), nullable=False),
    sa.Column('case_type', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('priority', sa.String(length=16), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('assigned_to', sa.String(length=128), nullable=True),
    sa.Column('source_signal_id', sa.String(length=36), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index('idx_compliance_case_tenant_created', 'compliance_cases', ['tenant_id', 'created_at'], unique=False, schema='public')
    op.create_index('idx_compliance_case_tenant_domain_status', 'compliance_cases', ['tenant_id', 'domain', 'status'], unique=False, schema='public')
    op.create_table('compliance_obligations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('domain', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('owner', sa.String(length=128), nullable=True),
    sa.Column('frequency', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('next_due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index('idx_obligation_tenant_domain', 'compliance_obligations', ['tenant_id', 'domain'], unique=False, schema='public')
    op.create_index('idx_obligation_tenant_status_due', 'compliance_obligations', ['tenant_id', 'status', 'next_due_at'], unique=False, schema='public')
    op.create_table('covenant_evaluations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('covenant_id', sa.String(length=36), nullable=False),
    sa.Column('snapshot_id', sa.String(length=36), nullable=False),
    sa.Column('metric_name', sa.String(length=128), nullable=False),
    sa.Column('metric_value', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('threshold', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('comparator', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('distance_pct', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('case_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index('idx_cov_eval_tenant_snapshot', 'covenant_evaluations', ['tenant_id', 'snapshot_id'], unique=False, schema='public')
    op.create_index('idx_cov_eval_tenant_status', 'covenant_evaluations', ['tenant_id', 'status'], unique=False, schema='public')
    op.create_table('esg_csrd_submissions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('assessment_batch_id', sa.String(length=36), nullable=False),
    sa.Column('metric_id', sa.String(length=36), nullable=True),
    sa.Column('metric_code', sa.String(length=64), nullable=False),
    sa.Column('reported_value', sa.Text(), nullable=True),
    sa.Column('reported_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('evidence_refs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('assurance_level', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index('idx_esg_sub_tenant_batch', 'esg_csrd_submissions', ['tenant_id', 'assessment_batch_id'], unique=False, schema='public')
    op.create_index('idx_esg_sub_tenant_status_created', 'esg_csrd_submissions', ['tenant_id', 'status', 'created_at'], unique=False, schema='public')
    op.create_table('esg_metrics',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('metric_code', sa.String(length=64), nullable=False),
    sa.Column('metric_name', sa.String(length=255), nullable=False),
    sa.Column('pillar', sa.String(length=1), nullable=False),
    sa.Column('reporting_frequency', sa.String(length=32), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('owner', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index('idx_esg_metric_tenant_code', 'esg_metrics', ['tenant_id', 'metric_code'], unique=False, schema='public')
    op.create_index('idx_esg_metric_tenant_status', 'esg_metrics', ['tenant_id', 'status'], unique=False, schema='public')
    op.create_table('financial_covenants',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('metric_name', sa.String(length=128), nullable=False),
    sa.Column('comparator', sa.String(length=8), nullable=False),
    sa.Column('threshold', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('warning_buffer_pct', sa.Numeric(precision=8, scale=3), nullable=False),
    sa.Column('frequency', sa.String(length=64), nullable=True),
    sa.Column('owner', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index('idx_covenant_tenant_metric', 'financial_covenants', ['tenant_id', 'metric_name'], unique=False, schema='public')
    op.create_index('idx_covenant_tenant_status', 'financial_covenants', ['tenant_id', 'status'], unique=False, schema='public')
    op.create_table('financial_snapshots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index('idx_fin_snapshot_tenant_period', 'financial_snapshots', ['tenant_id', 'period_end'], unique=False, schema='public')
    op.create_table('gdpr_processing_activities',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('activity_name', sa.String(length=255), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=True),
    sa.Column('lawful_basis', sa.String(length=64), nullable=True),
    sa.Column('data_categories', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('data_subjects', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('recipients', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('transfer_countries', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source_system', sa.String(length=128), nullable=True),
    sa.Column('dpa_reference', sa.String(length=128), nullable=True),
    sa.Column('owner', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('last_reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_review_due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index('idx_gdpr_ropa_tenant_review_due', 'gdpr_processing_activities', ['tenant_id', 'next_review_due_at'], unique=False, schema='public')
    op.create_index('idx_gdpr_ropa_tenant_status', 'gdpr_processing_activities', ['tenant_id', 'status'], unique=False, schema='public')
    op.create_table('gdpr_retention_findings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('snapshot_id', sa.String(length=36), nullable=False),
    sa.Column('policy_id', sa.String(length=36), nullable=True),
    sa.Column('system_name', sa.String(length=128), nullable=False),
    sa.Column('data_category', sa.String(length=128), nullable=False),
    sa.Column('observed_oldest_age_days', sa.Integer(), nullable=False),
    sa.Column('retention_days', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('excess_days', sa.Integer(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('case_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index('idx_gdpr_finding_tenant_snapshot', 'gdpr_retention_findings', ['tenant_id', 'snapshot_id'], unique=False, schema='public')
    op.create_index('idx_gdpr_finding_tenant_status_created', 'gdpr_retention_findings', ['tenant_id', 'status', 'created_at'], unique=False, schema='public')
    op.create_table('gdpr_retention_policies',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('system_name', sa.String(length=128), nullable=False),
    sa.Column('data_category', sa.String(length=128), nullable=False),
    sa.Column('legal_basis', sa.String(length=128), nullable=True),
    sa.Column('retention_days', sa.Integer(), nullable=False),
    sa.Column('warning_buffer_days', sa.Integer(), nullable=False),
    sa.Column('owner', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index('idx_gdpr_policy_tenant_status', 'gdpr_retention_policies', ['tenant_id', 'status'], unique=False, schema='public')
    op.create_index('idx_gdpr_policy_tenant_system_category', 'gdpr_retention_policies', ['tenant_id', 'system_name', 'data_category'], unique=False, schema='public')
    op.create_table('gdpr_retention_snapshots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index('idx_gdpr_snapshot_tenant_captured', 'gdpr_retention_snapshots', ['tenant_id', 'captured_at'], unique=False, schema='public')
    op.create_table('hs_incidents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('incident_ref', sa.String(length=64), nullable=False),
    sa.Column('site', sa.String(length=128), nullable=False),
    sa.Column('incident_type', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.String(length=32), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('lost_time_days', sa.Integer(), nullable=False),
    sa.Column('affected_people', sa.Integer(), nullable=False),
    sa.Column('narrative', sa.Text(), nullable=True),
    sa.Column('corrective_actions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('reported_to_authority_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index('idx_hs_incident_tenant_status', 'hs_incidents', ['tenant_id', 'status'], unique=False, schema='public')
    op.create_index('idx_hs_incident_tenant_type_date', 'hs_incidents', ['tenant_id', 'incident_type', 'occurred_at'], unique=False, schema='public')
    op.create_table('hs_riddor_assessments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('incident_id', sa.String(length=36), nullable=False),
    sa.Column('reportable', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('deadline_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('days_until_deadline', sa.Integer(), nullable=True),
    sa.Column('reasons', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index('idx_hs_riddor_tenant_incident', 'hs_riddor_assessments', ['tenant_id', 'incident_id'], unique=False, schema='public')
    op.create_index('idx_hs_riddor_tenant_status_created', 'hs_riddor_assessments', ['tenant_id', 'status', 'created_at'], unique=False, schema='public')
    op.create_table('rd_tax_activities',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('project_code', sa.String(length=128), nullable=False),
    sa.Column('activity_name', sa.String(length=255), nullable=False),
    sa.Column('activity_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('qualifying_category', sa.String(length=64), nullable=False),
    sa.Column('technical_uncertainty', sa.Boolean(), nullable=False),
    sa.Column('narrative_present', sa.Boolean(), nullable=False),
    sa.Column('staff_hours', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('cost_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('evidence_refs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index('idx_rd_tax_activity_tenant_project_date', 'rd_tax_activities', ['tenant_id', 'project_code', 'activity_date'], unique=False, schema='public')
    op.create_index('idx_rd_tax_activity_tenant_status', 'rd_tax_activities', ['tenant_id', 'status'], unique=False, schema='public')
    op.create_table('rd_tax_assessments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('assessment_batch_id', sa.String(length=36), nullable=False),
    sa.Column('project_code', sa.String(length=128), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_cost', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('qualifying_cost', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('qualifying_ratio_pct', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('missing_evidence_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('estimated_credit_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=True),
    sa.Column('reasons', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index('idx_rd_tax_assess_tenant_batch', 'rd_tax_assessments', ['tenant_id', 'assessment_batch_id'], unique=False, schema='public')
    op.create_index('idx_rd_tax_assess_tenant_status', 'rd_tax_assessments', ['tenant_id', 'status'], unique=False, schema='public')
    op.create_table('sar_reports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('jurisdiction', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('suspicion_summary', sa.Text(), nullable=False),
    sa.Column('narrative', sa.Text(), nullable=False),
    sa.Column('report_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('submission_reference', sa.String(length=128), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consent_deadline_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index('idx_sar_report_tenant_case', 'sar_reports', ['tenant_id', 'case_id'], unique=False, schema='public')
    op.create_index('idx_sar_report_tenant_status', 'sar_reports', ['tenant_id', 'status'], unique=False, schema='public')
    op.create_table('sla_contracts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('service_name', sa.String(length=128), nullable=False),
    sa.Column('metric_name', sa.String(length=128), nullable=False),
    sa.Column('comparator', sa.String(length=8), nullable=False),
    sa.Column('target_value', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('warning_buffer_pct', sa.Numeric(precision=8, scale=3), nullable=False),
    sa.Column('credit_rate_pct', sa.Numeric(precision=8, scale=3), nullable=False),
    sa.Column('max_credit_pct', sa.Numeric(precision=8, scale=3), nullable=False),
    sa.Column('monthly_contract_value', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('frequency', sa.String(length=64), nullable=True),
    sa.Column('owner', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index('idx_sla_contract_tenant_service_metric', 'sla_contracts', ['tenant_id', 'service_name', 'metric_name'], unique=False, schema='public')
    op.create_index('idx_sla_contract_tenant_status', 'sla_contracts', ['tenant_id', 'status'], unique=False, schema='public')
    op.create_table('sla_evaluations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('contract_id', sa.String(length=36), nullable=False),
    sa.Column('snapshot_id', sa.String(length=36), nullable=False),
    sa.Column('service_name', sa.String(length=128), nullable=False),
    sa.Column('metric_name', sa.String(length=128), nullable=False),
    sa.Column('observed_value', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('target_value', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('comparator', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('distance_pct', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('estimated_credit_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index('idx_sla_eval_tenant_snapshot', 'sla_evaluations', ['tenant_id', 'snapshot_id'], unique=False, schema='public')
    op.create_index('idx_sla_eval_tenant_status_created', 'sla_evaluations', ['tenant_id', 'status', 'created_at'], unique=False, schema='public')
    op.create_table('sla_snapshots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index('idx_sla_snapshot_tenant_period', 'sla_snapshots', ['tenant_id', 'period_end'], unique=False, schema='public')
    op.create_table('supplier_profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('supplier_name', sa.String(length=255), nullable=False),
    sa.Column('country', sa.String(length=64), nullable=True),
    sa.Column('criticality', sa.String(length=32), nullable=False),
    sa.Column('owner', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index('idx_supplier_profile_tenant_name', 'supplier_profiles', ['tenant_id', 'supplier_name'], unique=False, schema='public')
    op.create_index('idx_supplier_profile_tenant_status', 'supplier_profiles', ['tenant_id', 'status'], unique=False, schema='public')
    op.create_table('supplier_risk_assessments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('assessment_batch_id', sa.String(length=36), nullable=False),
    sa.Column('supplier_id', sa.String(length=36), nullable=True),
    sa.Column('supplier_name', sa.String(length=255), nullable=False),
    sa.Column('probability_default_pct', sa.Numeric(precision=8, scale=3), nullable=False),
    sa.Column('payment_delay_days', sa.Integer(), nullable=False),
    sa.Column('watchlist_hit', sa.Boolean(), nullable=False),
    sa.Column('covenant_breach_signal', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=128), nullable=True),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('reasons', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index('idx_supplier_risk_tenant_batch', 'supplier_risk_assessments', ['tenant_id', 'assessment_batch_id'], unique=False, schema='public')
    op.create_index('idx_supplier_risk_tenant_status_created', 'supplier_risk_assessments', ['tenant_id', 'status', 'created_at'], unique=False, schema='public')
    op.create_table('vault_tokens',
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=128), nullable=False),
    sa.Column('ciphertext', sa.LargeBinary(), nullable=False),
    sa.Column('nonce', sa.LargeBinary(), nullable=False),
    sa.Column('data_type', sa.String(length=64), nullable=False),
    sa.Column('agent_id', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('invalidated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('key_version', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('token', 'tenant_id'),
    schema='vault'
    )
    op.create_index('idx_vault_agent', 'vault_tokens', ['agent_id'], unique=False, schema='vault')
    op.create_index('idx_vault_expires', 'vault_tokens', ['expires_at'], unique=False, schema='vault')
    op.create_index('idx_vault_tenant_token', 'vault_tokens', ['tenant_id', 'token'], unique=True, schema='vault')
    op.create_index(op.f('ix_vault_vault_tokens_tenant_id'), 'vault_tokens', ['tenant_id'], unique=False, schema='vault')
    op.create_unique_constraint('uq_audit_log_entry_id', 'audit_log', ['entry_id'], schema='audit')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_audit_log_entry_id', 'audit_log', schema='audit', type_='unique')
    op.drop_index(op.f('ix_vault_vault_tokens_tenant_id'), table_name='vault_tokens', schema='vault')
    op.drop_index('idx_vault_tenant_token', table_name='vault_tokens', schema='vault')
    op.drop_index('idx_vault_expires', table_name='vault_tokens', schema='vault')
    op.drop_index('idx_vault_agent', table_name='vault_tokens', schema='vault')
    op.drop_table('vault_tokens', schema='vault')
    op.execute("DROP SCHEMA IF EXISTS vault")
    op.drop_index('idx_supplier_risk_tenant_status_created', table_name='supplier_risk_assessments', schema='public')
    op.drop_index('idx_supplier_risk_tenant_batch', table_name='supplier_risk_assessments', schema='public')
    op.drop_table('supplier_risk_assessments', schema='public')
    op.drop_index('idx_supplier_profile_tenant_status', table_name='supplier_profiles', schema='public')
    op.drop_index('idx_supplier_profile_tenant_name', table_name='supplier_profiles', schema='public')
    op.drop_table('supplier_profiles', schema='public')
    op.drop_index('idx_sla_snapshot_tenant_period', table_name='sla_snapshots', schema='public')
    op.drop_table('sla_snapshots', schema='public')
    op.drop_index('idx_sla_eval_tenant_status_created', table_name='sla_evaluations', schema='public')
    op.drop_index('idx_sla_eval_tenant_snapshot', table_name='sla_evaluations', schema='public')
    op.drop_table('sla_evaluations', schema='public')
    op.drop_index('idx_sla_contract_tenant_status', table_name='sla_contracts', schema='public')
    op.drop_index('idx_sla_contract_tenant_service_metric', table_name='sla_contracts', schema='public')
    op.drop_table('sla_contracts', schema='public')
    op.drop_index('idx_sar_report_tenant_status', table_name='sar_reports', schema='public')
    op.drop_index('idx_sar_report_tenant_case', table_name='sar_reports', schema='public')
    op.drop_table('sar_reports', schema='public')
    op.drop_index('idx_rd_tax_assess_tenant_status', table_name='rd_tax_assessments', schema='public')
    op.drop_index('idx_rd_tax_assess_tenant_batch', table_name='rd_tax_assessments', schema='public')
    op.drop_table('rd_tax_assessments', schema='public')
    op.drop_index('idx_rd_tax_activity_tenant_status', table_name='rd_tax_activities', schema='public')
    op.drop_index('idx_rd_tax_activity_tenant_project_date', table_name='rd_tax_activities', schema='public')
    op.drop_table('rd_tax_activities', schema='public')
    op.drop_index('idx_hs_riddor_tenant_status_created', table_name='hs_riddor_assessments', schema='public')
    op.drop_index('idx_hs_riddor_tenant_incident', table_name='hs_riddor_assessments', schema='public')
    op.drop_table('hs_riddor_assessments', schema='public')
    op.drop_index('idx_hs_incident_tenant_type_date', table_name='hs_incidents', schema='public')
    op.drop_index('idx_hs_incident_tenant_status', table_name='hs_incidents', schema='public')
    op.drop_table('hs_incidents', schema='public')
    op.drop_index('idx_gdpr_snapshot_tenant_captured', table_name='gdpr_retention_snapshots', schema='public')
    op.drop_table('gdpr_retention_snapshots', schema='public')
    op.drop_index('idx_gdpr_policy_tenant_system_category', table_name='gdpr_retention_policies', schema='public')
    op.drop_index('idx_gdpr_policy_tenant_status', table_name='gdpr_retention_policies', schema='public')
    op.drop_table('gdpr_retention_policies', schema='public')
    op.drop_index('idx_gdpr_finding_tenant_status_created', table_name='gdpr_retention_findings', schema='public')
    op.drop_index('idx_gdpr_finding_tenant_snapshot', table_name='gdpr_retention_findings', schema='public')
    op.drop_table('gdpr_retention_findings', schema='public')
    op.drop_index('idx_gdpr_ropa_tenant_status', table_name='gdpr_processing_activities', schema='public')
    op.drop_index('idx_gdpr_ropa_tenant_review_due', table_name='gdpr_processing_activities', schema='public')
    op.drop_table('gdpr_processing_activities', schema='public')
    op.drop_index('idx_fin_snapshot_tenant_period', table_name='financial_snapshots', schema='public')
    op.drop_table('financial_snapshots', schema='public')
    op.drop_index('idx_covenant_tenant_status', table_name='financial_covenants', schema='public')
    op.drop_index('idx_covenant_tenant_metric', table_name='financial_covenants', schema='public')
    op.drop_table('financial_covenants', schema='public')
    op.drop_index('idx_esg_metric_tenant_status', table_name='esg_metrics', schema='public')
    op.drop_index('idx_esg_metric_tenant_code', table_name='esg_metrics', schema='public')
    op.drop_table('esg_metrics', schema='public')
    op.drop_index('idx_esg_sub_tenant_status_created', table_name='esg_csrd_submissions', schema='public')
    op.drop_index('idx_esg_sub_tenant_batch', table_name='esg_csrd_submissions', schema='public')
    op.drop_table('esg_csrd_submissions', schema='public')
    op.drop_index('idx_cov_eval_tenant_status', table_name='covenant_evaluations', schema='public')
    op.drop_index('idx_cov_eval_tenant_snapshot', table_name='covenant_evaluations', schema='public')
    op.drop_table('covenant_evaluations', schema='public')
    op.drop_index('idx_obligation_tenant_status_due', table_name='compliance_obligations', schema='public')
    op.drop_index('idx_obligation_tenant_domain', table_name='compliance_obligations', schema='public')
    op.drop_table('compliance_obligations', schema='public')
    op.drop_index('idx_compliance_case_tenant_domain_status', table_name='compliance_cases', schema='public')
    op.drop_index('idx_compliance_case_tenant_created', table_name='compliance_cases', schema='public')
    op.drop_table('compliance_cases', schema='public')
    op.drop_index('idx_case_event_tenant_case_created', table_name='compliance_case_events', schema='public')
    op.drop_table('compliance_case_events', schema='public')
    op.drop_index('idx_comp_signal_tenant_status_created', table_name='competitor_signal_assessments', schema='public')
    op.drop_index('idx_comp_signal_tenant_batch', table_name='competitor_signal_assessments', schema='public')
    op.drop_table('competitor_signal_assessments', schema='public')
    op.drop_index('idx_competitor_profile_tenant_status', table_name='competitor_profiles', schema='public')
    op.drop_index('idx_competitor_profile_tenant_name', table_name='competitor_profiles', schema='public')
    op.drop_table('competitor_profiles', schema='public')
    op.drop_index('idx_aml_signal_tenant_status', table_name='aml_signals', schema='public')
    op.drop_index('idx_aml_signal_tenant_created', table_name='aml_signals', schema='public')
    op.drop_table('aml_signals', schema='public')
    op.drop_index('idx_agent_sec_policy_tenant', table_name='agent_security_policies', schema='public')
    op.drop_table('agent_security_policies', schema='public')
    op.drop_index('idx_agent_sec_decision_tenant_request', table_name='agent_security_decision_logs', schema='public')
    op.drop_index('idx_agent_sec_decision_tenant_created', table_name='agent_security_decision_logs', schema='public')
    op.drop_index('idx_agent_sec_decision_tenant_action', table_name='agent_security_decision_logs', schema='public')
    op.drop_table('agent_security_decision_logs', schema='public')
    # ### end Alembic commands ###
