"""Make masked_value nullable for erasure

Revision ID: b49cd746a4f6
Revises: e9368ac19ad2
Create Date: 2026-09-15 12:30:32.790290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b49cd746a4f6'
down_revision: Union[str, None] = 'e9368ac19ad2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('tenant_deletion_job_steps_job_id_fkey', 'tenant_deletion_job_steps', type_='foreignkey')
    op.create_foreign_key(None, 'tenant_deletion_job_steps', 'tenant_deletion_jobs', ['job_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint('tenant_deletion_jobs_tenant_id_fkey', 'tenant_deletion_jobs', type_='foreignkey')
    op.create_foreign_key(None, 'tenant_deletion_jobs', 'tenants', ['tenant_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint('tenant_policy_versions_tenant_id_fkey', 'tenant_policy_versions', type_='foreignkey')
    op.create_foreign_key(None, 'tenant_policy_versions', 'tenants', ['tenant_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint('users_tenant_id_fkey', 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'tenants', ['tenant_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.alter_column('pii_data_record', 'masked_value',
               existing_type=sa.VARCHAR(length=256),
               nullable=True,
               schema='gdpr')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pii_data_record', 'masked_value',
               existing_type=sa.VARCHAR(length=256),
               nullable=False,
               schema='gdpr')
    op.drop_constraint(None, 'users', schema='public', type_='foreignkey')
    op.create_foreign_key('users_tenant_id_fkey', 'users', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'tenant_policy_versions', schema='public', type_='foreignkey')
    op.create_foreign_key('tenant_policy_versions_tenant_id_fkey', 'tenant_policy_versions', 'tenants', ['tenant_id'], ['id'])
    op.drop_constraint(None, 'tenant_deletion_jobs', schema='public', type_='foreignkey')
    op.create_foreign_key('tenant_deletion_jobs_tenant_id_fkey', 'tenant_deletion_jobs', 'tenants', ['tenant_id'], ['id'])
    op.drop_constraint(None, 'tenant_deletion_job_steps', schema='public', type_='foreignkey')
    op.create_foreign_key('tenant_deletion_job_steps_job_id_fkey', 'tenant_deletion_job_steps', 'tenant_deletion_jobs', ['job_id'], ['id'])
    # ### end Alembic commands ###
