"""Add VaultKey and FailedAuditLog

Revision ID: c4dce1835471
Revises: 7c7ba7230531
Create Date: 2026-09-12 13:29:10.805457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c4dce1835471'
down_revision: Union[str, None] = '7c7ba7230531'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('failed_audit_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('agent_id', sa.String(length=128), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('failure_reason', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='audit'
    )
    op.create_index('idx_failed_audit_agent', 'failed_audit_log', ['agent_id', 'created_at'], unique=False, schema='audit')
    op.create_table('vault_keys',
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('encrypted_payload', sa.LargeBinary(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('version'),
    schema='vault'
    )
    op.drop_constraint('tenant_deletion_job_steps_job_id_fkey', 'tenant_deletion_job_steps', type_='foreignkey')
    op.create_foreign_key(None, 'tenant_deletion_job_steps', 'tenant_deletion_jobs', ['job_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint('tenant_deletion_jobs_tenant_id_fkey', 'tenant_deletion_jobs', type_='foreignkey')
    op.create_foreign_key(None, 'tenant_deletion_jobs', 'tenants', ['tenant_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint('tenant_policy_versions_tenant_id_fkey', 'tenant_policy_versions', type_='foreignkey')
    op.create_foreign_key(None, 'tenant_policy_versions', 'tenants', ['tenant_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint('users_tenant_id_fkey', 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'tenants', ['tenant_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', schema='public', type_='foreignkey')
    op.create_foreign_key('users_tenant_id_fkey', 'users', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'tenant_policy_versions', schema='public', type_='foreignkey')
    op.create_foreign_key('tenant_policy_versions_tenant_id_fkey', 'tenant_policy_versions', 'tenants', ['tenant_id'], ['id'])
    op.drop_constraint(None, 'tenant_deletion_jobs', schema='public', type_='foreignkey')
    op.create_foreign_key('tenant_deletion_jobs_tenant_id_fkey', 'tenant_deletion_jobs', 'tenants', ['tenant_id'], ['id'])
    op.drop_constraint(None, 'tenant_deletion_job_steps', schema='public', type_='foreignkey')
    op.create_foreign_key('tenant_deletion_job_steps_job_id_fkey', 'tenant_deletion_job_steps', 'tenant_deletion_jobs', ['job_id'], ['id'])
    op.drop_table('vault_keys', schema='vault')
    op.drop_index('idx_failed_audit_agent', table_name='failed_audit_log', schema='audit')
    op.drop_table('failed_audit_log', schema='audit')
    # ### end Alembic commands ###
