"""Add GDPR models

Revision ID: e9368ac19ad2
Revises: c4dce1835471
Create Date: 2026-09-12 13:30:46.440154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9368ac19ad2'
down_revision: Union[str, None] = 'c4dce1835471'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE SCHEMA IF NOT EXISTS gdpr')
    op.create_table('erasure_request',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('data_subject_id', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('records_deleted', sa.Integer(), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='gdpr'
    )
    op.create_index('idx_erasure_status', 'erasure_request', ['status'], unique=False, schema='gdpr')
    op.create_index('idx_erasure_tenant', 'erasure_request', ['tenant_id'], unique=False, schema='gdpr')
    op.create_table('pii_data_record',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('audit_log_id', sa.BigInteger(), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('masked_value', sa.String(length=256), nullable=False),
    sa.Column('processing_purpose', sa.String(length=256), nullable=False),
    sa.Column('legal_basis', sa.String(length=64), nullable=False),
    sa.Column('data_subject_id', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('retention_until', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='gdpr'
    )
    op.create_index('idx_pii_retention', 'pii_data_record', ['retention_until'], unique=False, schema='gdpr')
    op.create_index('idx_pii_subject', 'pii_data_record', ['data_subject_id'], unique=False, schema='gdpr')
    op.create_index('idx_pii_tenant', 'pii_data_record', ['tenant_id'], unique=False, schema='gdpr')
    op.drop_constraint('tenant_deletion_job_steps_job_id_fkey', 'tenant_deletion_job_steps', type_='foreignkey')
    op.create_foreign_key(None, 'tenant_deletion_job_steps', 'tenant_deletion_jobs', ['job_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint('tenant_deletion_jobs_tenant_id_fkey', 'tenant_deletion_jobs', type_='foreignkey')
    op.create_foreign_key(None, 'tenant_deletion_jobs', 'tenants', ['tenant_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint('tenant_policy_versions_tenant_id_fkey', 'tenant_policy_versions', type_='foreignkey')
    op.create_foreign_key(None, 'tenant_policy_versions', 'tenants', ['tenant_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint('users_tenant_id_fkey', 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'tenants', ['tenant_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', schema='public', type_='foreignkey')
    op.create_foreign_key('users_tenant_id_fkey', 'users', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'tenant_policy_versions', schema='public', type_='foreignkey')
    op.create_foreign_key('tenant_policy_versions_tenant_id_fkey', 'tenant_policy_versions', 'tenants', ['tenant_id'], ['id'])
    op.drop_constraint(None, 'tenant_deletion_jobs', schema='public', type_='foreignkey')
    op.create_foreign_key('tenant_deletion_jobs_tenant_id_fkey', 'tenant_deletion_jobs', 'tenants', ['tenant_id'], ['id'])
    op.drop_constraint(None, 'tenant_deletion_job_steps', schema='public', type_='foreignkey')
    op.create_foreign_key('tenant_deletion_job_steps_job_id_fkey', 'tenant_deletion_job_steps', 'tenant_deletion_jobs', ['job_id'], ['id'])
    op.drop_index('idx_pii_tenant', table_name='pii_data_record', schema='gdpr')
    op.drop_index('idx_pii_subject', table_name='pii_data_record', schema='gdpr')
    op.drop_index('idx_pii_retention', table_name='pii_data_record', schema='gdpr')
    op.drop_table('pii_data_record', schema='gdpr')
    op.drop_index('idx_erasure_tenant', table_name='erasure_request', schema='gdpr')
    op.drop_index('idx_erasure_status', table_name='erasure_request', schema='gdpr')
    op.drop_table('erasure_request', schema='gdpr')
    # ### end Alembic commands ###
